[build]
builder = "nixpacks"

[deploy]
startCommand = "python deploy.py"
healthcheckPath = "/docs"
healthcheckTimeout = 100

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python deploy.py"
