[build]
builder = "dockerfile"

[deploy]
startCommand = "python deploy.py"
healthcheckPath = "/health"
healthcheckTimeout = 100

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python deploy.py"
